routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::namespace('Faq')->group(function () {
    Route::get('/', 'AuthorController@index')->name('faq');
    Route::resource('faq', 'QuestionController')->only([
        'store'
    ]);
    Route::prefix('faq')->group(function () {  
        Route::get('categories/{category_id}', 'CategoryController@show')->name('categories.show');
        Route::get('questions/create/category/{category_id}','QuestionController@create')->name('faq.create');
    });        
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    
    Route::namespace('Admin')->group(function () {
        
        Route::resource('admin', 'AdminController')->only([
            'index','create', 'store', 'destroy','edit','update'
        ]);
        Route::prefix('admin')->group(function () {
            Route::get('/admin/updatelist/','AdminController@updatelist')->name('admin.updatelist');
            Route::get('/admin/destroylist/','AdminController@destroylist')->name('admin.destroylist');       
        });
        
        Route::resource('questions', 'QuestionController')->only([
            'index','edit', 'update'
        ]);
        Route::get('/questions/category/{category_id}','QuestionController@index')->name('questions.index');
        
        Route::resource('answers', 'AnswerController');
        Route::get('/answers/create/question/{question_id}', 'AnswerController@create')->name('answers.create');
        
        Route::resource('categories', 'CategoryController')->only([
            'index','create', 'store', 'destroy'
        ]);
        Route::get('/categories/destroylist', 'CategoryController@destroylist')->name('categories.destroylist');
    });
});

app/Http/Controllers/Faq/AuthorController.php
<?php

namespace FAQ\Http\Controllers\Faq;

use Illuminate\Http\Request;
use FAQ\Http\Controllers\Controller;
use FAQ\Author;
use FAQ\Category;

class AuthorController extends Controller
{
       
    public function index()
    { 
        $categories = Category::all();     
        return view('faq_main')->with('categories', $categories);
    }
}

app/Http/Controllers/Faq/CategoryController.php
<?php

namespace FAQ\Http\Controllers\Faq;

use Illuminate\Http\Request;
use FAQ\Http\Controllers\Controller;
use FAQ\Category;

class CategoryController extends Controller
{
    public function show($id)
    {
          $category = Category::find($id);
          $questions = $category->questionsFiltered;
          $categories = Category::all();     
          return view('faq.questions_by_category', compact('questions','categories','category'));      
    }
}

app/Http/Controllers/Faq/QuestionController.php
<?php

namespace FAQ\Http\Controllers\Faq;

use Illuminate\Http\Request;
use FAQ\Http\Controllers\Controller;
use FAQ\Question;
use FAQ\Category;
use FAQ\Author;

class QuestionController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($category_id)
    {
         $currentCategory = Category::find($category_id);
         $categories = Category::all();     
     	 return view('faq.ask_question')->with('currentCategory', $currentCategory)->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $author = Author::firstOrCreate(
        array(
                'name' => $request->name, 
                'email' => $request->email
        ));
        $question = Question::create(
        array(
            'category_id' =>$request->category_id, 
            'question' => $request->question, 
            'status_id' =>1, 
            'author_id' =>$author->id
        ));
       
       $categories = Category::all();   
       $currentCategory = Category::find($request->category_id);
       return view('faq.question_add_info')->with('currentCategory', $currentCategory)->with('author', $request->name)->with('email', $request->email)->with('question', $request->question)->with('categories',$categories);
    }
}

resources/views/faq/ask_question.blade.php
@extends('faq_main')

@section('questions')
<section class="questions">
    <div class="row  m-b-md align-items-center justify-content-between">
            <div class="col-6"><h3>Задать вопрос по категории  "{{ $currentCategory->category }}"</h3></div>
            <div class="col-6"><a href="{{ route('categories.show', ['id' => $currentCategory->id] ) }}">Вопросы и ответы категории "{{ $currentCategory->category }}"</a></div>
    </div>
    <form action="{{ route('faq.store') }}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="category_id" value="{{ $currentCategory->id }}">
        <div class="form-group">
            <label for="email">Введите Ваш email</label>
            <input type="email" class="form-control" id="email" aria-describedby="email" placeholder="Ваш email" name="email" required>
       </div>
       <div class="form-group">
            <label for="name">Введите Ваше имя</label>
            <input type="name" class="form-control" id="name" aria-describedby="name" placeholder="Ваше имя" name="name" required>
       </div>
       <div class="form-group">
            <label for="question">Задайте Ваш вопрос</label>
            <input type="question" class="form-control" id="question" aria-describedby="question" placeholder="Ваш вопрос" name="question" required>
       </div>
       <button type="submit" class="btn btn-primary">Задать вопрос</button>    
   </form>
 </section>        
@endsection

resources/views/faq/question_add_info.blade.php
@extends('faq_main')

@section('questions')
<section class="questions">
    <div class="row  m-b-md align-items-center justify-content-between">
            <div class="col-6"><a href="{{ route('categories.show', ['id' => $currentCategory->id] ) }}">Вопросы и ответы категории "{{ $currentCategory->category }}"</a></div>
            <div class="col-6"><a href="{{ route('faq.create', ['category_id' => $currentCategory->id ] ) }}">Задать вопрос по категории  "{{ $currentCategory->category }}"</a></div>
    </div>
    <h3>{{ $author }},</h3>
   <p>ваш вопрос: <i>"{{ $question }}"</i> направлен на обработку. Ответ на него будет отправлен на Вашу электронную почту {{ $email }} </p>
</section>        
@endsection

resources/views/faq/questions_by_category.blade.php
@extends('faq_main')

@section('questions')
<section class="questions">
    <div class="row  m-b-md align-items-center justify-content-between">    
        @if($questions->isEmpty()) 
            <div class="col-6"><h3>В категории "{{ $category->category }}" 
            нет вопросов для показа</h3></div>
            <div class="col-6"><a href="{{ route('faq.create', ['category_id' =>$category->id ]) }}">Задать вопрос по категории  "{{ $category->category}}"</a></div>
        @else
            <div class="col-6"><h3>Вопросы и ответы категории "{{ $category->category }}"</h3></div>
            <div class="col-6"><a href="{{ route('faq.create', ['category_id' =>$category->id ]) }}">Задать вопрос по категории  "{{ $category->category }}"</a></div>
    @endif
    </div>
    @foreach($questions as $question)
        <div  class="questions__item  m-b-md">
            <p>Вопрос задал: <i>{{ $question->author->name }}</i></p>
        	<p>Дата вопроса: <i>{{ $question->created_at }}</i></p>
        	<h4>Вопрос:</h4>
        	<p>{{ $question->question}}</p>           
        	<h4>Ответ на вопрос:</h4>
        	<p>{{ $question->answer['answer']}}</p>     
        </div>
    @endforeach
</section>        
@endsection