routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::namespace('Faq')->group(function () {
    Route::get('/', 'AuthorController@index')->name('faq');
    Route::resource('faq', 'QuestionController')->only([
        'store'
    ]);
    Route::prefix('faq')->group(function () {  
        Route::get('categories/{category_id}', 'CategoryController@show')->name('categories.show');
        Route::get('questions/create/category/{category_id}','QuestionController@create')->name('faq.create');
    });        
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    
    Route::namespace('Admin')->group(function () {
        
        Route::resource('admin', 'AdminController')->only([
            'index','create', 'store', 'destroy','edit','update'
        ]);
        Route::prefix('admin')->group(function () {
            Route::get('/admin/updatelist/','AdminController@updatelist')->name('admin.updatelist');
            Route::get('/admin/destroylist/','AdminController@destroylist')->name('admin.destroylist');       
        });
        
        Route::resource('questions', 'QuestionController')->only([
            'index','edit', 'update'
        ]);
        Route::get('/questions/category/{category_id}','QuestionController@index')->name('questions.index');
        
        Route::resource('answers', 'AnswerController');
        Route::get('/answers/create/question/{question_id}', 'AnswerController@create')->name('answers.create');
        
        Route::resource('categories', 'CategoryController')->only([
            'index','create', 'store', 'destroy'
        ]);
        Route::get('/categories/destroylist', 'CategoryController@destroylist')->name('categories.destroylist');
    });
});

resources/views/admin/admin_create.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Добавить администратора</h4>

    <form action="{{ route('admin.store')}}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label for="email">Введите email администратора</label>
            <input type="email" class="form-control" id="email" aria-describedby="email" placeholder="email администратора" name="email" required>
       </div>
       <div class="form-group">
            <label for="name">Введите имя администратора (name)</label>
            <input type="text" class="form-control" id="name" aria-describedby="name" placeholder="Имя администратора (name)" name="name" required>
       </div>
       <div class="form-group">
            <label for="username">Введите имя администратора (username)</label>
            <input type="text" class="form-control" id="username" aria-describedby="username" placeholder="Имя администратора (username)" name="username" required>
       </div>
       <div class="form-group">
            <label for="password">Введите пароль администратора</label>
            <input type="password" class="form-control" id="password" aria-describedby="password" placeholder="Пароль администратора" name="password" required>
       </div>
       <button type="submit" class="btn btn-primary">Добавить администратора</button>    
   </form>
   
 </div>   
@endsection

resources/views/admin/admin_edit.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Изменить пароль администратора</h4>
<table class="table">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Имя</th>
          <th scope="col">Email</th>
          <th scope="col">Дата изменения пароля</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">{{ $admin->id }}</th>
          <td>{{ $admin->name }}</td>
          <td>{{ $admin->email }}</td>
          <td>{{ $admin->updated_at }}</td>
        </tr>
      </tbody>
</table> 
    <form action="{{ route('admin.update', ['id_admin' => $admin->id ])}}" method="post">
       @method('PUT')
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label for="password">Введите новый пароль администратора</label>
            <input type="password" class="form-control" id="password" aria-describedby="password" placeholder="Пароль администратора" name="password" required>
       </div>
       <button type="submit" class="btn btn-primary">Изменить пароль</button>    
   </form>
   
 </div>   
@endsection

resources/views/admin/admin_edit_info.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>{{ $title }}</h4>
<table class="table">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Имя</th>
          <th scope="col">Email</th>
          <th scope="col">Дата изменения пароля</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">{{ $admin['id'] }}</th>
          <td>{{ $admin['name'] }}</td>
          <td>{{ $admin['email'] }}</td>
          <td>{{ $admin['updated_at'] }}</td>
        </tr>
      </tbody>
</table>    
 </div>   
@endsection

resources/views/admin/admins_list.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Список администраторов</h4>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Логин</th>
              <th scope="col">Email</th>
              <th scope="col">Создан</th>
              <th scope="col">Изменен</th>
            </tr>
         </thead>
        <tbody>
        @foreach($admins as $admin)
        <tr>
          <th scope="row">{{ $admin->id }}</th>
          <td>{{ $admin->name }}</td>
          <td>{{ $admin->email }}</td>
          <td>{{ $admin->created_at }}</td>
          <td>{{ $admin->updated_at }}</td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/admin/admins_list_2_edit.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Список администраторов для изменения пароля</h4>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Логин</th>
              <th scope="col">Email</th>
              <th scope="col">Создан</th>
              <th scope="col">Изменен</th>
              <th scope="col">Изменить пароль</th>
            </tr>
         </thead>
        <tbody>
        @foreach($admins as $admin)
        <tr>
          <th scope="row">{{ $admin->id }}</th>
          <td>{{ $admin->name }}</td>
          <td>{{ $admin->email }}</td>
          <td>{{ $admin->created_at }}</td>
          <td>{{ $admin->updated_at }}</td>
          <td><a href="{{ route('admin.edit', ['id' =>$admin->id]) }}" class="btn btn-primary">Изменить пароль</a></td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/admin/admins_list_2_remove.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Список администраторов для удаления</h4>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Логин</th>
              <th scope="col">Email</th>
              <th scope="col">Создан</th>
              <th scope="col">Изменен</th>
              <th scope="col">Удалить</th>
            </tr>
         </thead>
        <tbody>
        @foreach($admins as $admin)
        <tr>
          <th scope="row">{{ $admin->id }}</th>
          <td>{{ $admin->name }}</td>
          <td>{{ $admin->email }}</td>
          <td>{{ $admin->created_at }}</td>
          <td>{{ $admin->updated_at }}</td>
          <td>
            <form action="{{ route('admin.destroy', $admin->id ) }}" method="POST">
                @method('DELETE')
                @csrf
                <button class="btn btn-primary">Удалить</button>
            </form>
          </td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/admin/answer_create.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Изменить вопрос</h4>
    <form action="{{ route('answers.store' )}}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="id_question" value="{{ $question->id }}">
        <div class="form-group">
            <label for="question">Вопрос</label>
            <input type="text" class="form-control" id="question" aria-describedby="question" value="{{ $question->question  }}" name="question" disabled>
       </div>
       <div class="form-group">
            <label for="answer">Ответ на вопрос</label>
            <input type="text" class="form-control" id="answer" aria-describedby="answer" placeholder="Ответ на вопрос" name="answer" required>
       </div> 
       <div class="form-group">
            <label for="status">Статус вопроса</label>
            <select class="form-control" id="status_id" name="status_id">
              <option value="2" >Опубликован</option>
              <option value="3" >Скрыт</option>
            </select>
       </div> 
       <button type="submit" class="btn btn-primary">Сохранить</button>    
   </form>
   
 </div>   
@endsection

resources/views/admin/answer_edit.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Изменить вопрос</h4>
    <form action="{{ route('answers.update', ['id' => $question->answer->id ])}}" method="post">
        @method('PUT')
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label for="question">Вопрос</label>
            <input type="hidden" name="question_id" value="{{ $question->id }}">
            <input type="text" class="form-control" id="question" aria-describedby="question" value="{{ $question->question  }}" name="question" disabled>
       </div>
       <div class="form-group">
            <label for="answer">Ответ на вопрос</label>
            <input type="hidden" name="answer_id" value="{{ $question->answer->id }}">
            <input type="text" class="form-control" id="answer" aria-describedby="answer" value="{{ $question->answer->answer }}" name="answer">
       </div> 
       <div class="form-group">
            <label for="status">Статус вопроса</label>
            <select class="form-control" id="status_id" name="status_id">
              <option value="{{ $question->status->id  }}" selected>{{ $question->status->status }}</option>
              <option value="2" >Опубликован</option>
              <option value="3" >Скрыт</option>
            </select>
       </div> 
       <button type="submit" class="btn btn-primary">Изменить</button>    
   </form>
 </div>   
@endsection

resources/views/admin/categories_list.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Список категорий</h4>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Название</th>
              <th scope="col">Всего вопросов</th>
              <th scope="col">Опубликовано</th>
              <th scope="col">Без ответов</th>
              <th scope="col">Перейти к вопросам</th>
            </tr>
         </thead>
        <tbody>
        @foreach($allCategories as $category)
        <tr>
          <th scope="row">{{  $category->id }}</th>
          <td>{{  $category->category   }}</td>
          <td>{{ $category->questions()->count() }}</td>
          <td>{{ $category->questions()->active()->get()->count()  }}</td>
          <td>{{ $category->questions()->waiting()->get()->count() }}</td>
          <td><a href="{{ route('questions.index', ['id_category' => $category->id ]) }}" class="btn btn-primary">Перейти</a></td>    
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/admin/categories_list_2_remove.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Список категорий для удаления</h4>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Название</th>
              <th scope="col">Всего вопросов</th>
              <th scope="col">Опубликовано</th>
              <th scope="col">Без ответов</th>
              <th scope="col">Удалить</th>
            </tr>
         </thead>
        <tbody>
        @foreach($allCategories as $category)
        <tr>
          <th scope="row">{{  $category->id }}</th>
          <td>{{  $category->category   }}</td>
          <td>{{ $category->questions()->count() }}</td>
          <td>{{ $category->questions()->active()->where('category_id',  $category->id )->count() }}</td>
          <td>{{ $category->questions()->waiting()->where('category_id',  $category->id )->count() }}</td>
           <td>
            <form action="{{ route('categories.destroy', $category->id) }}" method="POST">
                @method('DELETE')
                @csrf
                <button class="btn btn-primary">Удалить категорию<br>и все вопросы в ней</button>
            </form>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/admin/category_create.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Добавить категорию</h4>
    <form action="{{ route('categories.store')}}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
       <div class="form-group">
            <label for="category">Название категории</label>
            <input type="text" class="form-control" id="category" aria-describedby="answer" placeholder="Название категории" name="category" required>
       </div> 
       <button type="submit" class="btn btn-primary">Сохранить</button>    
   </form>
   
 </div>   
@endsection

resources/views/admin/menu.blade.php
<div id="menu">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Администраторы
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{ route('admin.index') }}">Все администраторы</a>
          <a class="dropdown-item" href="{{ route('admin.create') }}">Добавить администратора</a>
          <a class="dropdown-item" href="{{ route('admin.updatelist') }}">Изменить пароль администратора</a>
          <a class="dropdown-item" href="{{ route('admin.destroylist') }}">Удалить администратора</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Категории вопросов
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{ route('categories.index') }}">Все категории</a>
          <a class="dropdown-item" href="{{ route('categories.create') }}">Добавить категорию</a>
          <a class="dropdown-item" href="{{ route('categories.destroylist') }}">Удалить категорию и все вопросы в ней</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

</div><!-- menu -->

resources/views/admin/question_edit.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Изменить вопрос</h4>
    <form action="{{ route('questions.update', ['id_question' => $question->id ])}}" method="post">
        @method('PUT')
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label for="question">Вопрос</label>
            <input type="text" class="form-control" id="question" aria-describedby="question" value="{{ $question->question }}" name="question">
       </div>
      <div class="form-group">
            <label for="created_at">Дата вопроса</label>
            <input type="text" class="form-control" id="created_at" aria-describedby="created_at" placeholder="{{ $question->created_at }}" name="created_at" disabled>
       </div>
      <div class="form-group">
            <label for="forCategory">Категория вопроса</label>
            <select class="form-control" id="category_id" name="category_id">
                  <option value="{{ $question->category->id }}" selected>{{ $question->category->category }}</option>
                  @foreach($categories as $category)
                    <option value="{{ $category->id  }}" >{{ $category->category }}</option>
                  @endforeach
            </select>
       </div>
       <div class="form-group">
            <label for="forAuthor">Автор вопроса</label>
            <select class="form-control" id="author_id" name="author_id">
              <option value="{{ $question->author->id  }}" selected>{{ $question->author->name }}</option>
              @foreach($authors as $author)
                <option value="{{ $author->id  }}" >{{ $author->name }}</option>
              @endforeach
            </select>
       </div>
        <div class="form-group">
            @if($question->answer)
                <label for="answer">Ответ на вопрос</label>
                <input type="text" class="form-control" id="answer" aria-describedby="answer" placeholder="{{ $question->answer->answer }}" name="answer" disabled>
            @endif
       </div> 
       <div class="form-group">
            <label for="status">Статус вопроса - "{{ $question->status->status }}"</label>
       </div> 
       <button type="submit" class="btn btn-primary">Изменить</button>    
       @if($question->answer)
            <a href="{{ route('answers.edit', ['id' => $question->id ] ) }}" class="btn btn-primary">Изменить ответ и статус вопроса</a>  
       @else
             <a href="{{ route('answers.create', ['question_id' => $question->id ] ) }}" class="btn btn-primary">Добавить ответ и изменить статус вопроса</a>  
       @endif
   </form>
   
 </div>   
@endsection

resources/views/admin/questions_list.blade.php
@extends('home')

@section('admin-content')
<div class="admin-content">
<h4>Список вопросов</h4>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Вопрос</th>
               <th scope="col">Категория</th>
              <th scope="col">Статус</th>
              <th scope="col">Дата вопроса</th>
              <th scope="col">Перейти к вопросу</th>
            </tr>
         </thead>
        <tbody>
        @foreach($questions as $question)
        <tr>
          <th scope="row">{{  $question->id }}</th>
          <td>{{  $question->question  }}</td>
          <td>{{ $question->category->category }}</td>
          <td>{{ $question->status->status }}</td>
          <td>{{ $question->created_at }}</td>
          <td><a href="{{ route('questions.edit', ['id_question' => $question->id] ) }}" class="btn btn-primary">Перейти</a></td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection